# Generated by Django 3.0.2 on 2020-01-22 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='Summary',
            new_name='summary',
        ),
    ]
