# Generated by Django 3.0.2 on 2020-01-22 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0002_auto_20200122_1526'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jobs',
            new_name='Job',
        ),
    ]
